import Image from "next/image";
import { Reveal } from "@/components/Reveal";
import { projects } from "@/lib/projects";

// Only sites whose demo is still deployed. A retired demo keeps its place in the
// Serbian gallery as design work, but it cannot sit under a "live now" caption.
const liveProjects = projects.filter((p) => p.liveUrl);

export const liveProjectCount = liveProjects.length;

export function LiveSiteStrip() {
  return (
    <ul className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
      {liveProjects.map((p, i) => (
        <Reveal key={p.slug} as="li" delay={i * 0.06} className="h-full">
          <a
            href={p.liveUrl as string}
            target="_blank"
            rel="noreferrer"
            className="card group flex h-full flex-col overflow-hidden transition-colors hover:border-line-strong"
          >
            <div
              className="overflow-hidden border-b border-line"
              style={{ borderTopWidth: 2, borderTopColor: p.accent }}
            >
              <Image
                src={p.image}
                alt={p.alt}
                sizes="(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw"
                placeholder="blur"
                className="w-full transition-transform duration-500 ease-out group-hover:scale-[1.015]"
              />
            </div>
            <div className="flex flex-1 flex-col p-4">
              <p className="font-display text-lg font-semibold tracking-tight">
                {p.name}
                <span className="ml-2 align-middle text-[12px] font-normal tracking-normal text-text-faint">
                  {p.kind}
                </span>
              </p>
              <p className="mono mt-2 text-[10.5px] tracking-wide text-text-faint">
                generated by the pipeline, live now ↗
              </p>
            </div>
          </a>
        </Reveal>
      ))}
    </ul>
  );
}
